// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFlHp3PU8mSHEJ-yoj8lsz6cz3dmkKGno',
    appId: '1:788128738393:web:9c0fa373c71733be281548',
    messagingSenderId: '788128738393',
    projectId: 'studentapp-9b01b',
    authDomain: 'studentapp-9b01b.firebaseapp.com',
    storageBucket: 'studentapp-9b01b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQaipZz8rR60Z2MkQYJNEbLNqhKQv95Kk',
    appId: '1:788128738393:android:063ccabba6ab8c92281548',
    messagingSenderId: '788128738393',
    projectId: 'studentapp-9b01b',
    storageBucket: 'studentapp-9b01b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe9oAM3_FrQG02I19Jp61gGpVvH8To_NU',
    appId: '1:788128738393:ios:642b64b757d06c01281548',
    messagingSenderId: '788128738393',
    projectId: 'studentapp-9b01b',
    storageBucket: 'studentapp-9b01b.firebasestorage.app',
    iosBundleId: 'com.example.studentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe9oAM3_FrQG02I19Jp61gGpVvH8To_NU',
    appId: '1:788128738393:ios:642b64b757d06c01281548',
    messagingSenderId: '788128738393',
    projectId: 'studentapp-9b01b',
    storageBucket: 'studentapp-9b01b.firebasestorage.app',
    iosBundleId: 'com.example.studentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFlHp3PU8mSHEJ-yoj8lsz6cz3dmkKGno',
    appId: '1:788128738393:web:7eb61c8ab32ddaf8281548',
    messagingSenderId: '788128738393',
    projectId: 'studentapp-9b01b',
    authDomain: 'studentapp-9b01b.firebaseapp.com',
    storageBucket: 'studentapp-9b01b.firebasestorage.app',
  );
}
